### ISSUE TITLE
maessentials /spawn crashes server

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/the-seilican-experience#14]
As stated above, doing /spawn will cause a server tick issue and crash the server

Crash report:
https://paste.ubuntu.com/p/MXz8vfCP4Z/

Cross referencing to maessentials now, crosslink incoming!!!!! Hold your horses!

**Comment by kreezxil** [comment]
and maessentials updated, no doubt to fix this. however, we're switching, let's let some other mod crash the server.
