### ISSUE TITLE
graves not spawning on death

### ISSUE THREAD

**Issue by Nazgoul9** [kreezxil/the-seilican-experience#17]
several times I have died and lost my stuff because the grave from [here](https://www.curseforge.com/minecraft/mc-mods/gravestone-lite) didn't spawn for me to pick it up.

**Comment by kreezxil** [comment]
in the new MC 1.15.1 version of the pack?

**Comment by Nazgoul9** [comment]
it is in the new 1.15.1 version of the pack on the server.

**Comment by kreezxil** [comment]
must be a problem with the grave mod that we installed. Shabbat is starting
I will have to look more into this tomorrow evening.
