### ISSUE TITLE
miner advantage is causing lag

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#18]
any time i mine a ore or fell a tree or it switches to the tool it causes me lag for at most i found 1 min

**Comment by kreezxil** [comment]
is this happening the minecraft 1.14.4 or the minecraft 1.15.1 version of
the pack? if you don't know what I'm talking about in Twitch left click the
pack icon and on the next screen it says forge version, give me that line.

In GDL, when you left click the pack icon, the right side information panel
changes to show you which forge version.

**Comment by flyingbluesnake** [comment]
i can't use GDL I'm using Atlauncher on 1.15.1-2.0.1

**Comment by Seilican** [comment]
the tool switching thing can be turned off in commands
