### ISSUE TITLE
Mod request 

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#20]
**CJ and i are requesting that these be added to the mod pack in the next 
update**
https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

https://www.curseforge.com/minecraft/mc-mods/deathquotes-death-quotes

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire

https://www.curseforge.com/minecraft/mc-mods/redstone-furnaces

https://www.curseforge.com/minecraft/mc-mods/bad-beacon

https://www.curseforge.com/minecraft/mc-mods/security-craft

https://www.curseforge.com/minecraft/mc-mods/nethercraft-classic

https://www.curseforge.com/minecraft/mc-mods/more-ores-in-one

https://www.curseforge.com/minecraft/mc-mods/cursed

https://www.curseforge.com/minecraft/mc-mods/experienceore

https://www.curseforge.com/minecraft/mc-mods/diamond-in-the-rough

https://www.curseforge.com/minecraft/mc-mods/simple-void-world

https://www.curseforge.com/minecraft/mc-mods/cursed-earth

https://www.curseforge.com/minecraft/mc-mods/unstable-tools

https://www.curseforge.com/minecraft/mc-mods/cha-s

https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar

https://www.curseforge.com/minecraft/mc-mods/quickteleports

https://www.curseforge.com/minecraft/mc-mods/goprone

https://www.curseforge.com/minecraft/mc-mods/double-doors

https://www.curseforge.com/minecraft/mc-mods/stronghold-compass

https://www.curseforge.com/minecraft/mc-mods/just-player-heads

https://www.curseforge.com/minecraft/mc-mods/enchanted-wolves

https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs

**Comment by Seilican** [comment]
https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks
do not want to change what we know how works

https://www.curseforge.com/minecraft/mc-mods/deathquotes-death-quotes
just fluff that would upset lady every once in a while

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire
busted server once

https://www.curseforge.com/minecraft/mc-mods/redstone-furnaces
too OP

https://www.curseforge.com/minecraft/mc-mods/bad-beacon
effects Minecolonies villagers so will be problems 

https://www.curseforge.com/minecraft/mc-mods/security-craft
no make's raiding no fun

https://www.curseforge.com/minecraft/mc-mods/nethercraft-classic
too much / too heavy

https://www.curseforge.com/minecraft/mc-mods/more-ores-in-one
do not need more weapons

https://www.curseforge.com/minecraft/mc-mods/cursed
one's paying for server do not want

https://www.curseforge.com/minecraft/mc-mods/experienceore
world gen happened and just a drop in the bucket not worth it

https://www.curseforge.com/minecraft/mc-mods/diamond-in-the-rough
cheat mod no

https://www.curseforge.com/minecraft/mc-mods/simple-void-world
making more dem's per block kills tps

https://www.curseforge.com/minecraft/mc-mods/cursed-earth
over powered no

https://www.curseforge.com/minecraft/mc-mods/unstable-tools
over powered no

https://www.curseforge.com/minecraft/mc-mods/cha-s
we wanted it but its fabric

https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar
Yes this is first Add so far

https://www.curseforge.com/minecraft/mc-mods/quickteleports
2nd yes

https://www.curseforge.com/minecraft/mc-mods/goprone
npc's can't go prone so no

https://www.curseforge.com/minecraft/mc-mods/double-doors
do not need a mod just open doors

https://www.curseforge.com/minecraft/mc-mods/stronghold-compass
over powered

https://www.curseforge.com/minecraft/mc-mods/just-player-heads
pvp Yes add 3rd one

https://www.curseforge.com/minecraft/mc-mods/enchanted-wolves
was asked for found out it was fabric

https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs
4th yes please add

**Comment by kreezxil** [comment]
these are a lot of mods, I recommend a new pack to built with these
changes. As far as what you want Seilican from their suggestions. Make a
new list below this comment with the mods that you do want from their list
above. Reading through the list above to find what you want to add is a bit
annoying to me.

Considering all the packs I update and lately the modding that I've gotten
back into.

Btw, NOPOLES is ready for 1.14.4 and 1.15.1 you remember that one, stops
the nerd poles.
