### ISSUE TITLE
update please

### ISSUE THREAD

**Issue by Seilican** [kreezxil/the-seilican-experience#21]
Remove list

Useless Mod
Additional Enchanted Miner

Please add list

https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar

https://www.curseforge.com/minecraft/mc-mods/quickteleports

https://www.curseforge.com/minecraft/mc-mods/just-player-heads

https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs

Thank you

**Comment by kreezxil** [comment]
done, I'll have this out shortly.

**Comment by kreezxil** [comment]
ok, well you guys need to verify the forge version against the version you're running.

Overloaded Armor is for 1.15, not 1.15.x so it won't go in.

**Comment by kreezxil** [comment]
ok, that's the only way that didn't make it in, now if these new ones don't crash anything, you're golden.

**Comment by kreezxil** [comment]
hit a snag, pinged you and minecolonies dev about in the discord.

**Suggestion:** rebuild for 1.15.2 as minecolonies team is not deleting that branch when it appears on CF.
