### ISSUE TITLE
hut blocks not placing

### ISSUE THREAD

**Issue by Nazgoul9** [kreezxil/the-seilican-experience#23]
this has happened a couple of times now but when I try to place the barracks block, the block is used and yet it doesn't place down in the world. I also experienced this issue when I tried to first place my townhall block. I do everything the same way with the other hut blocks and they worked just fine.

**Comment by kreezxil** [comment]
ok, thanks for letting me know. Consider going to
https://github.com/ldtteam/minecolonies/issues and seeing if someone has
reported it and if there has been a solution presented.

**Comment by kreezxil** [comment]
@Nazgoul9 did you go there? did you find a related issue or start a new one? if either, please paste a copy of the link here so we can remote track it.

Otherwise we'll close this.

**Comment by Nazgoul9** [comment]
I did look and I didn't see anyone else having the same problem. I did leave an issue report [here](https://github.com/ldtteam/minecolonies/issues/4321) but I don't feel like its an issue with mine colonies because nobody else on the TSE server is having this issue and I can't replicate it on a solo world.

**Comment by Nazgoul9** [comment]
I just restarted the game and its working now

**Comment by kreezxil** [comment]
looks like they fixed it. the fix will be the next official update.
