### ISSUE TITLE
1.15.2 update please

### ISSUE THREAD

**Issue by Seilican** [kreezxil/the-seilican-experience#24]
update please for 1.15.2

Please add
https://refinedstorage.raoulvdberge.com/releases/195
Refined Storage
or
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files

https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

https://www.curseforge.com/minecraft/mc-mods/maessentials

Removes please

Doggy Talents
Lava Monsters
Solar Generation

**Comment by kreezxil** [comment]
these changes have been applied.

I'm now grabbing the updates and testing the changes for obvy issues.

should have this out very shortly tonight.
