### ISSUE TITLE
please add mods in next update

### ISSUE THREAD

**Issue by Nazgoul9** [kreezxil/the-seilican-experience#25]
[soul shard respawn](https://www.curseforge.com/minecraft/mc-mods/soul-shards-respawn)

[wither skeleton tweaks](https://www.curseforge.com/minecraft/mc-mods/wither-skeleton-tweaks)

[more dragon eggs](https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)

**Comment by kreezxil** [comment]
I like how you put "adding" in the title vs "please add"

**Comment by kreezxil** [comment]
now we just need @Seilican to sign off on it.

**Comment by kreezxil** [comment]
i'll add these in todays patch, as they are not burdensome on a radish level pc and won't change the gameplay to any noticeable effect except for those that need lots of dragon eggs.

**Comment by kreezxil** [comment]
Just realized that Soul Shards mod is fabric and so I must ask you to remember to research if the mod is fabric, rift, or forge before suggesting it.

**Comment by Nazgoul9** [comment]
I looked further down on the page and I did find a forge version [here](https://www.curseforge.com/minecraft/mc-mods/soul-shards-respawn/files/2880603)

**Comment by kreezxil** [comment]
the lesson then is link to me the exact file that is forge in the future.
now open a new ticket with just this mod and just that link in it. I'll add
it next update.

**Comment by kreezxil** [comment]
added

**Comment by kreezxil** [comment]
don't know why this was open, the mods are already there.
