### ISSUE TITLE
refined storage has no power

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#26]
we are unable to use any of the refined storage blocks without power please give us a mod to have power or maybe please change the config files so that the blocks do not require power?

**Comment by kreezxil** [comment]
Interesting that @Seilican didn't catch that. I'll update the pack with outdated mods and add in a power mod for this.

I won't add in any of the requests until I get a directive from Seilican to actually install the suggestions.
