### ISSUE TITLE
Me joining crashes the server

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#27]
Whenever I join I appear dead and in the server immediately crashes I know it is not a chunk error because I had a friend go over there and found my grave my username is purple_dragon42

**Comment by kreezxil** [comment]
are you crashing too?

**Comment by flyingbluesnake** [comment]
when i join the whole server crashes

**Comment by kreezxil** [comment]
ok, I know what the problem is; releasing a patch to fix it.
