### ISSUE TITLE
My minecolonies guis are glitched

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#28]
most of my minecolony blocks are missing a part of the gui the town hall is the most noticeable block with the allies and permission right page being missing yet i can still click on them. this is from my knowledge only on my computer i have tried reseting my modpack and it doesn't work

![2020-04-11_22 07 51](https://user-images.githubusercontent.com/8303375/79060359-58a2bc80-7c41-11ea-9083-1064e090cca3.png)
![2020-04-11_22 08 06](https://user-images.githubusercontent.com/8303375/79060361-5cceda00-7c41-11ea-87a8-4c7f2337c632.png)
![2020-04-11_22 09 37](https://user-images.githubusercontent.com/8303375/79060362-5d677080-7c41-11ea-8838-027ce92f278c.png)
![2020-04-11_22 09 40](https://user-images.githubusercontent.com/8303375/79060363-5e000700-7c41-11ea-92fb-ea87c825e938.png)

**Comment by kreezxil** [comment]
Why are the graphics askew for the rest of your minecraft world?

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/79070487-d4315780-7c9b-11ea-8420-999bc30c6734.png)

This means that I need to update your pack regardless of whether you guys finalized any new additions or removals.
