### ISSUE TITLE
Potential adds and removes for TSE

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/the-seilican-experience#3]
(Discord copy and paste below)
eaglereaperYesterday at 8:13 PM
suggest add Just Enough Resources (JER)
https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
 
eaglereaperYesterday at 8:25 PM
https://www.curseforge.com/minecraft/mc-mods/antique-atlas
https://www.curseforge.com/minecraft/mc-mods/click-machine
https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms
 
eaglereaperYesterday at 8:55 PM
https://www.curseforge.com/minecraft/mc-mods/solargeneration

**Comment by CriswellCodes** [comment]
# This is currently a Discussion only, will add labels later or have labels added.

**Comment by Seilican** [comment]
https://www.curseforge.com/minecraft/mc-mods/antique-atlas
https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
https://www.curseforge.com/minecraft/mc-mods/cha-s
https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads

are the ones we want to add so far

**Comment by Seilican** [comment]
Removes wanted so far
Named Areas
Draw Bridge
Speedy Hoppers
Speedy Ladders
tool belts
Simple Storage Network

**Comment by CriswellCodes** [comment]
Independent issues created for each addition and removal request. All requests include name of mod, author of mod, and the version of the mod incase future reversal is needed. For additions links to the mods are provided from the list above.

# WILL KEEP THIS ISSUE OPEN FOR DISCUSSION AND TRACKING PURPOSES. WILL UPDATE TAGS ONCE ALL MODIFICATIONS ARE MADE.

**Comment by kreezxil** [comment]
Thanks @Tarlin83 the overkill was really helpful, please do that again!
