### ISSUE TITLE
mine colonies block placing gui pop up/colony delete gui

### ISSUE THREAD

**Issue by Nazgoul9** [kreezxil/the-seilican-experience#30]
when i and some of the other players load into the game we cant access any of the normal hut block gui and I have a problem where it keeps asking if I want to place a block or use the build tool. The other two players that I know of, cant access their town hall GUI because it says that they already own a colony at the same coordinates that the town hall is at. when they enter my colony they get the same pop up I get. the pop up is so frequent that you cant enter the pause menu to quit the game sometimes.

![The Seilican Experience 4_22_2020 1_32_23 PM](https://user-images.githubusercontent.com/42102268/80025617-2ba2a500-849e-11ea-8ef1-8e589dbc7bca.png)
![The Seilican Experience 4_22_2020 1_28_37 PM](https://user-images.githubusercontent.com/42102268/80025624-2e04ff00-849e-11ea-9eb2-d51f8f65826c.png)

**Comment by kreezxil** [comment]
fixed in 2.9.10
