### ISSUE TITLE
builder A.I. ran into an issue

### ISSUE THREAD

**Issue by Nazgoul9** [kreezxil/the-seilican-experience#34]
i went to see what my builder was doing and  he gave me this message
![The Seilican Experience 5_7_2020 2_24_45 PM](https://user-images.githubusercontent.com/42102268/81341295-84616880-906e-11ea-9b4a-3d20a11b0c16.png)
i was wondering if a server admin would be able to help with this problem or if I'm just s.o.l.

**Comment by kreezxil** [comment]
you're s.o.l. for the time being, I'm asking the developer if it's been
fixed. if it has, I'll push another pack update. NO ETA on that as I'm
currently working on an issue with FORESHADOWING.

**Comment by kreezxil** [comment]
fixed in today's release
