### ISSUE TITLE
no more recipe type mod for 1.15.2

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/the-seilican-experience#38]
https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by Nazgoul9** [comment]
is there a way for this mod to work with furnace recipe conflicts?

**Comment by kreezxil** [comment]
We're gonna find out. If you see furnace recipe conflicts, let me know so I
can use craftweaker to fix them.

**Comment by kreezxil** [comment]
added

**Comment by Nazgoul9** [comment]
there is a recipe conflict with smelting vile dust and soul glass. both require that you smelt soul sand

**Comment by kreezxil** [comment]
did you test with polymorph to see if it rectifies it? I'll see what I can
do about this later today.

**Comment by kreezxil** [comment]
later today ended up being applied to BTMCGS due largely in part to my own biological systems lockup issues. I know EXTRA right. ok. I'll give this a look at tomorrow. 1st thing on my agenda.

**Comment by kreezxil** [comment]
fixed today.

**Comment by kreezxil** [comment]
While this is closed on my side because I'm correcting it using crafttweaker, this is where I reported it to polymorph as a feature request for smelting type recipes. and similar machines where an action is performed on a thing and the outcome could be in conflict. https://github.com/TheIllusiveC4/Polymorph/issues/8
