### ISSUE TITLE
Add Mod: Antique Atlas

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/the-seilican-experience#4]
requested mod:
https://www.curseforge.com/minecraft/mc-mods/antique-atlas

Crosslink for request:
https://github.com/kreezxil/the-seilican-experience/issues/3

**Comment by kreezxil** [comment]
added

**Comment by kreezxil** [comment]
sorry not added this mod is only for fabric

![image](https://user-images.githubusercontent.com/3880072/68550030-8bac0000-03c4-11ea-9963-a77aee9a209a.png)
