### ISSUE TITLE
Mod Removal: Named Areas

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/the-seilican-experience#8]
Requested removal:
Named Areas	Serilum	nmdar_1.14-3.8.jar

crosslink for request:
https://github.com/kreezxil/the-seilican-experience/issues/3

**Comment by kreezxil** [comment]
done

**Comment by Seilican** [comment]
ok thank you for info

**Comment by kreezxil** [comment]
no i thought i didn't upload it but it was there, stupid dev used a weird name for it.
